namespace Smb3Editor.App;

// Generated from Foundry objects.dat (dev branch, audited 2026-07-13).
// Keep this data set-specific: generator encodings are not shared merely because IDs match.
internal static class FoundryObjectCatalog
{
    private static readonly IReadOnlyDictionary<int, ObjectSet> Sets = new Dictionary<int, ObjectSet>
    {
        [1] = new(
            FixedObjects:
            [
                new(0, "Background Hills A"),
                new(1, "Background Hills B"),
                new(2, "Background Hills C"),
                new(3, "White Mushrooms"),
                new(4, "Door (CAN go in)"),
                new(5, "Door (CAN'T go in)"),
                new(6, "Vine extending downwards"),
                new(7, "Small Background Cloud"),
                new(16, "'?' with Flower"),
                new(17, "'?' with Leaf"),
                new(18, "'?' with Star"),
                new(19, "'?' with Continuous star"),
                new(20, "'?' with Single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "White Block Platform (Extends to ground)"),
                new(1, "Orange Block Platform (Extends to ground)"),
                new(2, "Green Block Platform (Extends to ground)"),
                new(3, "Blue Block Platform (Extends to ground)"),
                new(4, "White Block Platform (Floating)"),
                new(5, "Orange Block Platform (Floating)"),
                new(6, "Green Block Platform (Floating)"),
                new(7, "Blue Block Platform (Floating)"),
                new(8, "Background Bushes"),
                new(9, "Gap"),
                new(10, "Cloud Platform"),
                new(11, "Flat Ground"),
                new(12, "Underwater Flat Ground"),
                new(13, "Background Clouds"),
                new(14, "Underwater gap"),
                new(15, "Bricks"),
                new(16, "'?' Blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden Blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "Cloud Platform"),
            ]),
        [2] = new(
            FixedObjects:
            [
                new(0, "Door"),
                new(2, "Rotodisc block"),
                new(3, "Castle Room Background"),
                new(4, "Hot Foot Candle"),
                new(5, "Bowser Statue"),
                new(6, "Invisible Door"),
                new(7, "The Princess's Door"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "Bottom of background with pillars A"),
                new(1, "Bottom of background with pillars B"),
                new(2, "Red bricks"),
                new(3, "Dungeon background"),
                new(4, "Dark dungeon background"),
                new(5, "Dungeon windows"),
                new(6, "Long dungeon windows"),
                new(7, "Middle section of dungeon windows"),
                new(8, "Dungeon Lamps (Note: extends to ceiling)"),
                new(10, "Stretch platform"),
                new(11, "Floor Spikes"),
                new(12, "Ceiling Spikes"),
                new(13, "Horizontally oriented X-blocks"),
                new(14, "Vertically oriented X-blocks"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blocks with circles in the middle"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "Dark Dungeon Background"),
                new(46, "Dark Dungeon Background"),
                new(47, "Blank Background (used to block out stuff)"),
                new(48, "Lava"),
                new(49, "Conveyor Belt - moves left"),
                new(50, "Conveyor Belt - moves right"),
                new(51, "Horizontal Platform Wire"),
                new(52, "1 Platform Wire"),
                new(53, "45 Degree Platform Wire - Down/Right"),
                new(54, "45 Degree Platform Wire - Up/Right"),
                new(55, "60 Degree Platform Wire - Down/Right"),
                new(56, "60 Degree Platform Wire - Down/Left"),
                new(57, "Red Bricks - found in Bowser's Castle"),
                new(58, "Donut Blocks"),
            ]),
        [3] = new(
            FixedObjects:
            [
                new(0, "Upper Left Hill Corner - UnderGround"),
                new(1, "Upper Left Hill Corner - Hilly"),
                new(2, "Upper Left Hill Corner - UnderWater"),
                new(3, "Upper Right Hill Corner - UnderGround"),
                new(4, "Upper Right Hill Corner - Hilly"),
                new(5, "Upper Right Hill Corner - UnderWater"),
                new(7, "Lower Left Hill Corner"),
                new(8, "Lower Left Hill Corner - UnderWater"),
                new(10, "Lower Right Hill Corner"),
                new(11, "Lower Right Hill Corner - UnderWater"),
                new(14, "Sets proper background color (?)"),
                new(15, "Door"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
                new(42, "Background Hills A"),
                new(43, "Background Hills B"),
                new(44, "Background Hills C"),
                new(46, "Underground Background under this"),
                new(48, "Underground Tunnel A"),
                new(49, "Underground Tunnel B"),
                new(50, "45 Degree Diagonal Hill Strip A"),
                new(51, "45 Degree Diagonal Hill Strip B"),
                new(52, "Horizontal Hill Strip"),
                new(53, "1 Hill Strip"),
                new(54, "30 Degree Diagonal Hill Strip A"),
                new(55, "30 Degree Diagonal Hill Strip B"),
                new(56, "Triangular Hill Object A"),
                new(57, "Triangular Hill Object B"),
                new(58, "Steps A"),
                new(59, "Steps B"),
                new(60, "Square Hill Object"),
                new(61, "Flat Land & Water Pits"),
                new(62, "30-Degree Hill & Water Pits A"),
                new(63, "30-Degree Hill & Water Pits B"),
                new(64, "Small Background Cloud"),
            ],
            VariableObjects:
            [
                new(0, "45 Degree Underground Hill - Down/Right"),
                new(1, "45 Degree Underground Hill - Down/Left"),
                new(4, "45 Degree Hill - Down/Right"),
                new(5, "45 Degree Hill - Down/Left"),
                new(6, "45 Degree Hill - Up/Left"),
                new(7, "45 Degree Hill - Up/Right"),
                new(8, "45 Degree Underwater Hill - Down/Right"),
                new(9, "45 Degree Underwater Hill - Down/Left"),
                new(10, "45 Degree Underwater Hill - Up/Left"),
                new(11, "45 Degree Underwater Hill - Up/Right"),
                new(12, "Underground Wall - Left Side"),
                new(13, "Hilly Wall - Left Side"),
                new(14, "Dark Underground Wall - Left Side"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(42, "Normal Quicksand"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "30 Degree Underground Hill - Down/Right"),
                new(46, "30 Degree Underground Hill - Down/Left"),
                new(49, "30 Degree Hill - Down/Right"),
                new(50, "30 Degree Hill - Down/Left"),
                new(51, "30 Degree Hill - Up/Left"),
                new(52, "30 Degree Hill - Up/Right"),
                new(53, "30 Degree Underwater Hill - Down/Right"),
                new(54, "30 Degree Underwater Hill - Down/Left"),
                new(55, "30 Degree Underwater Hill - Up/Left"),
                new(56, "30 Degree Underwater Hill - Up/Right"),
                new(57, "Underground Wall - Right Side"),
                new(58, "Hilly Wall - Right Side"),
                new(59, "Dark Underground Wall - Right Side"),
                new(60, "Gap"),
                new(61, "Gap with Black Stars (Underground levels only)"),
                new(62, "Water"),
                new(63, "Underground Wall"),
                new(64, "Hilly Wall"),
                new(65, "Dark Underground Wall"),
                new(66, "Flat Land - Underground"),
                new(67, "Flat Land - Hilly"),
                new(68, "Flat Land - Underwater"),
                new(70, "Ceiling"),
                new(71, "Underwater Ceiling"),
                new(72, "Small Background Hills"),
                new(73, "Upward Pipe to End of Level"),
                new(75, "Background like at bottom of hilly level"),
                new(77, "Background Clouds"),
                new(79, "Hilly Wall - 50=right"),
                new(80, "Flat Ground with green on top (SMAS only)"),
            ]),
        [4] = new(
            FixedObjects:
            [
                new(0, "Small Swirly Background Cloud"),
                new(1, "Large Swirly Background Cloud"),
                new(2, "Blue Background Pole A"),
                new(3, "Blue Background Pole B"),
                new(4, "Wooden Background Pole"),
                new(5, "Door"),
                new(7, "Blue gear"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "Wooden platform"),
                new(1, "Wooden block platform"),
                new(3, "Background Bushes"),
                new(4, "Double Background Bushes"),
                new(5, "Green platform"),
                new(7, "Horizontal platform wire"),
                new(8, "1 platform wire"),
                new(9, "45 Degree Platform Wire - Down/Right"),
                new(10, "45 Degree Platform Wire - Up/Right"),
                new(12, "60 Degree Platform Wire - Down/Right"),
                new(13, "60 Degree Platform Wire - Down/Left"),
                new(14, "World 5-style Cloud Platform"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue Wooden Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(48, "Donut Blocks"),
                new(49, "Conveyor Belt - moves left"),
                new(50, "Conveyor Belt - moves right"),
                new(51, "Jelectros"),
                new(53, "Cloud Platform"),
                new(54, "Munchers"),
            ]),
        [5] = new(
            FixedObjects:
            [
                new(0, "Piranha Plant Muncher A"),
                new(1, "Piranha Plant Muncher B"),
                new(5, "Background Mountain"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "Giant cloud platform"),
                new(1, "Giant bricks"),
                new(2, "Giant '?' blocks with coins"),
                new(3, "Giant '?' blocks with leafs"),
                new(4, "Giant Wooden Blocks"),
                new(5, "Giant Metal Blocks"),
                new(6, "Giant Ground"),
                new(7, "Giant Downward Pipe"),
                new(8, "Giant Underwater Coral"),
                new(9, "Piranha Plant Small Downward Pipe A"),
                new(10, "Piranha Plant Small Downward Pipe B"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(47, "Horizontal no-ended pipe"),
                new(48, "Gap"),
                new(49, "Upward Pipe to End of Level"),
                new(50, "Rightward Pipe to End of Level"),
                new(51, "Lava"),
            ]),
        [6] = new(
            FixedObjects:
            [
                new(0, "Upper-left corner of curved pipe"),
                new(1, "Upper-right corner of curved pipe"),
                new(2, "Lower-left corner of curved pipe"),
                new(3, "Lower-right corner of curved pipe"),
                new(4, "Upward directional platform"),
                new(5, "Rightward directional platform"),
                new(6, "Leftward directional platform"),
                new(7, "Multi-directional directional platform"),
                new(10, "Door"),
                new(12, "Background for pipe levels"),
                new(13, "Water - lasts whole level"),
                new(16, "'?' with Flower"),
                new(17, "'?' with Leaf"),
                new(18, "'?' with Star"),
                new(19, "'?' with Continuous star"),
                new(20, "'?' with Single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "Double-ended pipe"),
                new(1, "Rightward pipe"),
                new(2, "Leftward pipe"),
                new(3, "Downward background pipe"),
                new(4, "Small vertical background pipe"),
                new(5, "Rightward background pipe"),
                new(6, "Leftward background pipe"),
                new(7, "Small Horizontal background pipe"),
                new(12, "Background Aquatic Plants"),
                new(13, "Vertically Oriented Donut Blocks"),
                new(14, "Ceiling Spikes"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "Upward Pipe"),
                new(46, "Rightward Pipe"),
                new(47, "Water - 2 blocks high"),
                new(48, "Gray platform"),
                new(49, "Orange Block Platform"),
                new(50, "Water - Horizontally Oriented"),
                new(51, "Water - Vertically Oriented"),
                new(52, "Jelectros"),
                new(53, "Double Ended Small Horizontal Pipe"),
                new(54, "Horizontally Oriented Donut Blocks"),
                new(55, "Donut Blocks"),
                new(56, "Floor Spikes"),
                new(57, "Water"),
            ]),
        [7] = new(
            FixedObjects:
            [
                new(0, "Background Hills A"),
                new(1, "Background Hills B"),
                new(2, "Background Hills C"),
                new(3, "White Mushrooms"),
                new(4, "Door (CAN go in)"),
                new(5, "Door (CAN'T go in)"),
                new(6, "Vine extending downwards"),
                new(7, "Small Background Cloud"),
                new(16, "'?' with Flower"),
                new(17, "'?' with Leaf"),
                new(18, "'?' with Star"),
                new(19, "'?' with Continuous star"),
                new(20, "'?' with Single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "White Block Platform (Extends to ground)"),
                new(1, "Orange Block Platform (Extends to ground)"),
                new(2, "Green Block Platform (Extends to ground)"),
                new(3, "Blue Block Platform (Extends to ground)"),
                new(4, "White Block Platform (Floating)"),
                new(5, "Orange Block Platform (Floating)"),
                new(6, "Green Block Platform (Floating)"),
                new(7, "Blue Block Platform (Floating)"),
                new(8, "Background Bushes"),
                new(9, "Gap"),
                new(10, "Cloud Platform"),
                new(11, "Flat Ground"),
                new(12, "Underwater Flat Ground"),
                new(13, "Background Clouds"),
                new(14, "Underwater gap"),
                new(15, "Bricks"),
                new(16, "'?' Blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden Blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "Cloud Platform"),
            ]),
        [8] = new(
            FixedObjects:
            [
                new(0, "Upper-left corner of curved pipe"),
                new(1, "Upper-right corner of curved pipe"),
                new(2, "Lower-left corner of curved pipe"),
                new(3, "Lower-right corner of curved pipe"),
                new(4, "Upward directional platform"),
                new(5, "Rightward directional platform"),
                new(6, "Leftward directional platform"),
                new(7, "Multi-directional directional platform"),
                new(10, "Door"),
                new(12, "Background for pipe levels"),
                new(13, "Water - lasts whole level"),
                new(16, "'?' with Flower"),
                new(17, "'?' with Leaf"),
                new(18, "'?' with Star"),
                new(19, "'?' with Continuous star"),
                new(20, "'?' with Single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "Double-ended pipe"),
                new(1, "Rightward pipe"),
                new(2, "Leftward pipe"),
                new(3, "Downward background pipe"),
                new(4, "Small vertical background pipe"),
                new(5, "Rightward background pipe"),
                new(6, "Leftward background pipe"),
                new(7, "Small Horizontal background pipe"),
                new(12, "Background Aquatic Plants"),
                new(13, "Vertically Oriented Donut Blocks"),
                new(14, "Ceiling Spikes"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "Upward Pipe"),
                new(46, "Rightward Pipe"),
                new(47, "Water - 2 blocks high"),
                new(48, "Gray platform"),
                new(49, "Orange Block Platform"),
                new(50, "Water - Horizontally Oriented"),
                new(51, "Water - Vertically Oriented"),
                new(52, "Jelectros"),
                new(53, "Double Ended Small Horizontal Pipe"),
                new(54, "Horizontally Oriented Donut Blocks"),
                new(55, "Donut Blocks"),
                new(56, "Floor Spikes"),
                new(57, "Water"),
            ]),
        [9] = new(
            FixedObjects:
            [
                new(0, "Small block pyramid - Extends to ground"),
                new(1, "Medium block pyramid - Extends to ground"),
                new(3, "Large block pyramid - Extends to ground"),
                new(4, "Palm Tree"),
                new(5, "Purple Bullet Bill Machine"),
                new(7, "Uncracked Pipe"),
                new(8, "Cracked Pipe"),
                new(9, "Bottom post of pipe structure"),
                new(10, "Oval Background Cloud"),
                new(11, "Door"),
                new(12, "Background Pyramid"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "Small block platforms"),
                new(1, "Medium block platforms"),
                new(2, "Large block platforms"),
                new(3, "X-Large block platforms"),
                new(4, "Diagonally oriented block platforms"),
                new(5, "Small sandstone blocks"),
                new(6, "Medium sandstone blocks"),
                new(7, "Large sandstone blocks"),
                new(8, "X-Large sandstone blocks"),
                new(9, "Diagonally oriented sandstone blocks"),
                new(10, "Small block platforms"),
                new(11, "Medium block platforms"),
                new(12, "Large block platforms"),
                new(13, "X-Large Block Platforms"),
                new(14, "Ice blue platform"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "1 Background Pole"),
                new(46, "Background Coconuts"),
                new(47, "Floor Spikes"),
                new(48, "Ceiling Spikes"),
                new(49, "Square Sandstone Blocks"),
                new(50, "Cloud Platform"),
                new(51, "Background Chains A"),
                new(52, "Background Chains B"),
                new(53, "Horizontal Plain Background A (used to block out stuff)"),
                new(54, "Pipe Boxes A"),
                new(55, "1 Plain Background (used to block out stuff)"),
                new(56, "Horizontal Plain Background B (used to block out stuff)"),
                new(59, "CAUTION: Screws Up Game"),
                new(63, "Pipe Boxes B"),
            ]),
        [10] = new(
            FixedObjects:
            [
                new(0, "Right Screw Head"),
                new(1, "2-Way Bullet Shooter"),
                new(2, "Rocket Engine"),
                new(3, "Wooden ship beam terminus A"),
                new(4, "Anchor"),
                new(5, "Top Screw Head"),
                new(6, "Bullet Shooter - Up/Left"),
                new(7, "Bullet Shooter - Up/Right"),
                new(8, "Bullet Shooter - Down/Left"),
                new(9, "Bullet Shooter - Down/Right"),
                new(10, "4-Way Bullet Shooter A"),
                new(11, "4-Way Bullet Shooter B"),
                new(12, "Metal Plated Bullet Shooter A"),
                new(13, "Metal Plated Bullet Shooter B"),
                new(14, "Wooden Background Box"),
                new(15, "Black boss room background"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
                new(42, "Wooden ship beam terminus B"),
                new(43, "Background wooden ship beam terminus"),
                new(44, "Tank A"),
                new(45, "Tank B"),
                new(46, "Corner of Airship - Lasts 32 Blocks"),
                new(47, "Left terminus of wooden tank beam"),
                new(48, "Rocky Wrench hole"),
                new(49, "Ship Platform A"),
                new(50, "Ship Platform B"),
            ],
            VariableObjects:
            [
                new(0, "Wooden Ship Beam"),
                new(1, "Wooden Ship Beam"),
                new(2, "Wooden Ship Beam with 2 strips of wood"),
                new(3, "Wooden Ship Pillar"),
                new(4, "Row of Wooden Ship Pillars"),
                new(5, "Thick Wooden Ship Beam"),
                new(6, "Corkscrew - Left terminus"),
                new(7, "Corkscrew - Right terminus"),
                new(8, "Corkscrew - Lower terminus"),
                new(9, "Corkscrew - Upper terminus"),
                new(10, "Metal platform"),
                new(11, "1 Metal Bar A"),
                new(12, "1 Metal Bar B"),
                new(13, "Thick vertical Background Pillar"),
                new(14, "1 Background Pillar"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "Wooden Ship Background Line"),
                new(46, "Railings"),
                new(47, "Ground (like on tank levels)"),
                new(48, "Metal box platform"),
                new(49, "Crate"),
                new(50, "Portholes"),
                new(51, "Wooden Tank Beam"),
                new(52, "Leftward Giant Bullet Shooter"),
                new(53, "Rightward Giant Bullet Shooter"),
                new(54, "Leftward Bullet Shooter"),
                new(55, "Tank Wheels"),
                new(56, "Invisible Platform"),
                new(61, "Tank C"),
            ]),
        [11] = new(
            FixedObjects:
            [
                new(0, "Piranha Plant Muncher A"),
                new(1, "Piranha Plant Muncher B"),
                new(5, "Background Mountain"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "Giant cloud platform"),
                new(1, "Giant bricks"),
                new(2, "Giant '?' blocks with coins"),
                new(3, "Giant '?' blocks with leafs"),
                new(4, "Giant Wooden Blocks"),
                new(5, "Giant Metal Blocks"),
                new(6, "Giant Ground"),
                new(7, "Giant Downward Pipe"),
                new(8, "Giant Underwater Coral"),
                new(9, "Piranha Plant Small Downward Pipe A"),
                new(10, "Piranha Plant Small Downward Pipe B"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(47, "Horizontal no-ended pipe"),
                new(48, "Gap"),
                new(49, "Upward Pipe to End of Level"),
                new(50, "Rightward Pipe to End of Level"),
                new(51, "Lava"),
            ]),
        [12] = new(
            FixedObjects:
            [
                new(4, "Wooden Background Pole"),
                new(5, "Door"),
                new(7, "Blue gear"),
                new(16, "'?' with Flower"),
                new(17, "'?' with Leaf"),
                new(18, "'?' with Star"),
                new(19, "'?' with Continuous star"),
                new(20, "'?' with Single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(0, "Icy flat ground"),
                new(2, "Green topped wooden platform"),
                new(3, "Top of snowy platform"),
                new(6, "Snowy Platform"),
                new(7, "Horizontal platform wire"),
                new(8, "1 platform wire"),
                new(9, "45 Degree Platform Wire - Down/Right"),
                new(10, "45 Degree Platform Wire - Up/Right"),
                new(11, "Background Clouds"),
                new(12, "60 Degree Platform Wire - Down/Right"),
                new(13, "60 Degree Platform Wire - Down/Left"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue Wooden Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "Ice Blocks"),
                new(46, "Frozen Munchers"),
                new(47, "Frozen Coins"),
                new(48, "Donut Blocks"),
                new(49, "Conveyor Belt - moves left"),
                new(50, "Conveyor Belt - moves right"),
                new(51, "Jelectros"),
                new(52, "Large Ice Blocks"),
                new(54, "Munchers"),
            ]),
        [13] = new(
            FixedObjects:
            [
                new(2, "Cloud Background A"),
                new(3, "Sets background to actual background color"),
                new(6, "Cloud Background B"),
                new(7, "Cloud Background C"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
            ],
            VariableObjects:
            [
                new(11, "World 5-style Cloud Platform - Blue Background"),
                new(12, "World 5-style Cloud Platform - White Background"),
                new(13, "Clouds C"),
                new(14, "World 6-style Cloud Platform"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "Clouds A"),
                new(46, "Clouds B"),
                new(47, "Horizontal no-ended pipe"),
                new(48, "Cloud-colored Background"),
                new(49, "1 no-ended pipe"),
                new(50, "Rightward pipe to end of level"),
                new(56, "Cloud-colored Background"),
            ]),
        [14] = new(
            FixedObjects:
            [
                new(0, "Upper Left Hill Corner - UnderGround"),
                new(1, "Upper Left Hill Corner - Hilly"),
                new(2, "Upper Left Hill Corner - UnderWater"),
                new(3, "Upper Right Hill Corner - UnderGround"),
                new(4, "Upper Right Hill Corner - Hilly"),
                new(5, "Upper Right Hill Corner - UnderWater"),
                new(7, "Lower Left Hill Corner"),
                new(8, "Lower Left Hill Corner - UnderWater"),
                new(10, "Lower Right Hill Corner"),
                new(11, "Lower Right Hill Corner - UnderWater"),
                new(15, "Door"),
                new(16, "'?' with flower"),
                new(17, "'?' with leaf"),
                new(18, "'?' with star"),
                new(19, "'?' with continuous star"),
                new(20, "'?' with single coin"),
                new(21, "Muncher"),
                new(22, "Brick with Flower"),
                new(23, "Brick with Leaf"),
                new(24, "Brick with Star"),
                new(25, "Brick with Continuous Star"),
                new(26, "Brick with Multi-Coin"),
                new(27, "Brick with 1-up"),
                new(28, "Brick with Vine"),
                new(29, "Brick with P-Switch"),
                new(30, "Invisible Coin"),
                new(31, "Invisible 1-up"),
                new(32, "Invisible Note Block"),
                new(33, "Note Block with Flower"),
                new(34, "Note Block with Leaf"),
                new(35, "Note Block with Star"),
                new(36, "Wooden Block with Flower"),
                new(37, "Wooden Block with Leaf"),
                new(38, "Wooden Block with Star"),
                new(39, "Red Invisible Note Block"),
                new(40, "P-Switch"),
                new(41, "Level Ending"),
                new(42, "Background Hills A"),
                new(43, "Background Hills B"),
                new(44, "Background Hills C"),
                new(45, "Blue background"),
                new(46, "Starry background"),
                new(48, "Underground Tunnel A"),
                new(49, "Underground Tunnel B"),
                new(50, "45 Degree Diagonal Hill Strip A"),
                new(51, "45 Degree Diagonal Hill Strip B"),
                new(52, "Horizontal Hill Strip"),
                new(53, "1 Hill Strip"),
                new(54, "30 Degree Diagonal Hill Strip A"),
                new(55, "30 Degree Diagonal Hill Strip B"),
                new(56, "Triangular Hill Object A"),
                new(57, "Triangular Hill Object B"),
                new(58, "Steps A"),
                new(59, "Steps B"),
                new(60, "Square Hill Object"),
                new(61, "Flat Land & Water Pits"),
                new(62, "30-Degree Hill & Water Pits A"),
                new(63, "30-Degree Hill & Water Pits B"),
                new(64, "Small Background Cloud"),
            ],
            VariableObjects:
            [
                new(0, "45 Degree Underground Hill - Down/Right"),
                new(1, "45 Degree Underground Hill - Down/Left"),
                new(4, "45 Degree Hill - Down/Right"),
                new(5, "45 Degree Hill - Down/Left"),
                new(6, "45 Degree Hill - Up/Left"),
                new(7, "45 Degree Hill - Up/Right"),
                new(8, "45 Degree Underwater Hill - Down/Right"),
                new(9, "45 Degree Underwater Hill - Down/Left"),
                new(10, "45 Degree Underwater Hill - Up/Left"),
                new(11, "45 Degree Underwater Hill - Up/Right"),
                new(12, "Underground Wall - Left Side"),
                new(13, "Hilly Wall - Left Side"),
                new(14, "Dark Underground Wall - Left Side"),
                new(15, "Bricks"),
                new(16, "'?' blocks with single coins"),
                new(17, "Bricks with single coins"),
                new(18, "Wooden blocks"),
                new(19, "Colored Note Blocks - movable four directions"),
                new(20, "Note Blocks - movable two directions"),
                new(21, "Wooden Blocks - movable"),
                new(22, "Coins"),
                new(23, "Downward Pipe (CAN go down)"),
                new(24, "Downward Pipe (CAN'T go down)"),
                new(25, "Downward Pipe (CAN go down"),
                new(26, "Upward Pipe (CAN go up)"),
                new(27, "Upward Pipe (CAN'T go up)"),
                new(28, "Rightward Pipe (CAN go in)"),
                new(29, "Rightward Pipe (CAN'T go in)"),
                new(30, "Leftward Pipe (CAN go in)"),
                new(31, "Leftward Pipe (CAN'T go in)"),
                new(32, "Bullet Bill Machine"),
                new(33, "Bridge"),
                new(34, "Silver Coins (appear when you hit a P-Switch)"),
                new(35, "Waterfall"),
                new(36, "Water (moves to left)"),
                new(37, "Water (still)"),
                new(38, "Water (moves to right)"),
                new(39, "Background used in Bowser's Castle"),
                new(40, "Blue X-Blocks"),
                new(42, "Normal Quicksand"),
                new(43, "White Turtle Bricks"),
                new(44, "Double-Ended vertical Pipe"),
                new(45, "30 Degree Underground Hill - Down/Right"),
                new(46, "30 Degree Underground Hill - Down/Left"),
                new(49, "30 Degree Hill - Down/Right"),
                new(50, "30 Degree Hill - Down/Left"),
                new(51, "30 Degree Hill - Up/Left"),
                new(52, "30 Degree Hill - Up/Right"),
                new(53, "30 Degree Underwater Hill - Down/Right"),
                new(54, "30 Degree Underwater Hill - Down/Left"),
                new(55, "30 Degree Underwater Hill - Up/Left"),
                new(56, "30 Degree Underwater Hill - Up/Right"),
                new(57, "Underground Wall - Right Side"),
                new(58, "Hilly Wall - Right Side"),
                new(59, "Dark Underground Wall - Right Side"),
                new(60, "Gap"),
                new(61, "Gap with Black Stars (Underground levels only)"),
                new(62, "Water"),
                new(63, "Underground Wall"),
                new(64, "Hilly Wall"),
                new(65, "Dark Underground Wall"),
                new(66, "Flat Land - Underground"),
                new(67, "Flat Land - Hilly"),
                new(68, "Flat Land - Underwater"),
                new(70, "Ceiling"),
                new(71, "Underwater Ceiling"),
                new(72, "Small Background Hills"),
                new(73, "Upward Pipe to End of Level"),
                new(75, "Background like at bottom of hilly level"),
                new(77, "Background Clouds"),
                new(79, "Hilly Wall - 50=right"),
                new(80, "Flat Ground with green on top (SMAS only)"),
            ]),
    };

    public static IReadOnlyList<NamedLevelObject> FixedForTileset(int tileset) =>
        Sets.TryGetValue(tileset, out var set) ? set.FixedObjects : [];

    public static IReadOnlyList<NamedLevelObject> VariableForTileset(int tileset) =>
        Sets.TryGetValue(tileset, out var set) ? set.VariableObjects : [];

    private sealed record ObjectSet(IReadOnlyList<NamedLevelObject> FixedObjects, IReadOnlyList<NamedLevelObject> VariableObjects);
}
